
  /funds:
    get:
     summary: Get all fundss
     tags: [funds]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/funds'
 
    post:
      summary: Create funds
      tags: [funds]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/funds'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/funds'
 
  /funds/{id}:
    get:
      summary: Get funds by id
      tags: [funds]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/funds'
 
    put:
      summary: Edit funds
      tags: [funds]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/funds'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/funds'
 
    delete:
      summary: Delete funds
      tags: [funds]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/funds'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  components:
    schemas:
  
      funds:
        type: object
        properties:
      
          id:
            type: string
          name:
            type: string
          entity:
            type: string
          user:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          gender:
            type: string
          age:
            type: number
          password:
            type: string
          phone:
            type: string